name: FCC-forAMstudent
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - pyaml
  - xrootd
  - uproot
  - awkward
  - numba
  - pyarrow
  - pandas
  - matplotlib
  - vector
  - tqdm
  - scikit-learn
  - jupyter
